app.py
from flask import Flask
from views import main

app = Flask(__name__)
app.register_blueprint(main)

if __name__ == "__main__":
    app.run(debug=True)

views.py
"""This code imports necessary modules from Flask, including Blueprint, render_template, request, jsonify, redirect, and url_for. It then creates a Blueprint named "main", which is a way to organize routes and views in Flask."""

from flask import Blueprint, render_template, request, jsonify, redirect, url_for

main = Blueprint("main", __name__)


@main.route("/")
def home():
    return render_template("index.html")

@main.route("/about")
def about():
    context = {
        "name": "Devi",
        "description": "Adpative. Energetic.  Verstile Product Program Manager. itae. Eum maxime et, amet itaque aliquam incidunt qui magnam id officia voluptate sequi quidem ut. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis quisquam provident consectetur expedita quaerat odit sit voluptates laborum debitis est laboriosam corrupti ratione, aperiam, sed odio cumque quas dolor esse pariatur voluptatem, placeat eum vitae. Eum maxime et, amet itaque aliquam incidunt qui magnam id officia voluptate sequi quidem ut!",
    }
    return render_template("about.html", context=context)

@main.route('/about-us')
def about_us():
    return redirect(url_for("main.about"))

@main.route("/contact")
def contact():
    return render_template("contact.html")

@main.route("/portfolio")
def portfolio():
    projects_list = [
        {'name': 'Taskmate', 'description': 'This is the first project.', 'endpoint': 'taskmate'},
        {'name': 'Codebook', 'description': 'This is the second project.', 'endpoint': 'codebook'},
        {'name': 'Codebook1', 'description': 'This is the third project.', 'endpoint': 'codebook1'}
    ]
    return render_template("portfolio.html", projects=projects_list)

@main.route("/portfolio/<project>")
def project(project):
    projects_lst = ["taskmate", "codebook", "codebook1"]
    if project in projects_lst:
        return render_template(f"portfolio/{project}.html")
    else:
        return redirect("/404")
    
@main.route('/portfolio/json')
def portfolio_json():
    projects = {
        "taskmate": {
            "langauge": "python",
            "framework": "django",
            "status": "completed"
        },
        "codebook": {
            "langauge": "javascript",
            "framework": "react",
            "status": "learning"
        },
        "codebook1": {
            "langauge": "javascript",
            "framework": "react",
            "status": "learning"
        }

    }
    return jsonify(projects)
    
@main.route("/s")
def search():
    keyword = request.args.get("k")
    return f"{keyword}"

@main.route('/404')
def not_found_404():
    return render_template("404.html"), 404

@main.app_errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1>About {{ context.name }}</h1>
    <img src="{{ url_for('static', filename='images/about.jpg') }}" alt="">
    <p>{{ context.description }}</p>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} - Portfolyx</title>

    <link rel="shortcut icon" href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon">
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a href="{{ url_for('main.home') }}">Home</a>
                </li>
                <li>
                    <a href="{{ url_for('main.about') }}">About</a>
                </li>
                <li>
                    <a href="{{ url_for('main.contact') }}">Contact</a>
                </li>
                <li>
                    <a href="{{ url_for('main.portfolio') }}">Portfolio</a>
                </li>
            </ul>
        </nav>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>    
    <footer>
        <p>&copy; 2025 - Portfolyx</p>
    </footer>    
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock %}

{% block content %}
    <h1>Let's Talk!</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati, illum atque! Illum architecto, Obcaecati, illum atque! Illum architecto, odit possimus quibusdam reiciendis accusantium sed corporis?</p>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, deleniti.</p>
    <p>Write to me at <strong>priyamadurai2022@gmail.com</strong></p>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Hi, I'm Devi Karuppiah!</h1>
    <p>I am an experienced program and product manager</p>
    <p>This website is to hold all my projects  dolor labore facilis suscipit vel, harum facere vero itaque laboriosam atque id error expedita deleniti ratione corporis consequatur voluptates debitis! </p>


{% endblock %}



templates/portfolio.html
{% extends 'base.html' %}

{% block title %}Portfolio{% endblock %}

{% block content %}

    <section>
        <h1>Portfolio</h1>
        <p>Things that I read . Quae quidem beatae soluta ea incidunt. Quidem odit sequi enim similique, quisquam maiores, suscipit consequatur voluptatum in perspiciatis, mollitia fugit? Incidunt aliquam nihil esse consequuntur perspiciatis inventore corporis, iure numquam labore placeat minus? Minima laudantium doloremque et ipsa fugiat nesciunt mollitia dolorum!</p>
    </section>

    <section class="projects">
        <h1>Projects</h1>
        {% for project in projects %}
            <div class="project">
                <h2><a href="portfolio/{{ project.endpoint }}">{{ project.name }}</a></h2>
                <p>{{ project.description }}</p>
            </div>
        {% endfor %}
    </section>    
    
{% endblock %}






    

templates/portfolio/codebook.html
{% extends 'base.html' %}

{% block title %}CodeBook Project{% endblock %}

{% block content %}
    <h1>About CodeBook</h1>
    <img src="{{ url_for('static', filename='images/project.jpg') }}" alt="">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam iusto illum, delectus consequuntur distinctio quam adipisci animi aliquid? Molestias distinctio ratione quis minus quia eum autem beatae veniam accusamus, culpa vero quasi eligendi quidem aliquid vel nostrum deleniti labore doloribus dolorem obcaecati officia velit dicta provident accusantium? Sunt, magni suscipit!</p>
{% endblock %}

templates/portfolio/codebook1.html
{% extends 'base.html' %}

{% block title %}CodeBook Project{% endblock %}

{% block content %}
    <h1>About CodeBook</h1>
    <img src="{{ url_for('static', filename='images/project.jpg') }}" alt="">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam iusto illum, delectus consequuntur distinctio quam adipisci animi aliquid? Molestias distinctio ratione quis minus quia eum autem beatae veniam accusamus, culpa vero quasi eligendi quidem aliquid vel nostrum deleniti labore doloribus dolorem obcaecati officia velit dicta provident accusantium? Sunt, magni suscipit!</p>
{% endblock %}

templates/portfolio/taskmate.html
{% extends 'base.html' %}

{% block title %}Taskmate Project{% endblock %}

{% block content %}
    <h1>About Taskmate</h1>
    <img src="{{ url_for('static', filename='images/project.jpg') }}" alt="">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam iusto illum, delectus consequuntur distinctio quam adipisci animi aliquid? Molestias distinctio ratione quis minus quia eum autem beatae veniam accusamus, culpa vero quasi eligendi quidem aliquid vel nostrum deleniti labore doloribus dolorem obcaecati officia velit dicta provident accusantium? Sunt, magni suscipit!</p>
{% endblock %}